const alunos = [
{'id':'12682', 'curso': 'ENGENHARIA DE PESCA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'70988', 'curso': 'ZOOTECNIA', 'entrada': '2018.2', 'status': 'DESISTENCIA'},
{'id':'10766', 'curso': 'BACHARELADO EM SISTEMAS DE INFORMAÇÃO', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'12158', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'13308', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'07095', 'curso': 'AGRONOMIA', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'08789', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'10335', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2016.2', 'status': 'TRANCAMENTO'},
{'id':'11924', 'curso': 'ZOOTECNIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'10083', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'10217', 'curso': 'BACHARELADO EM SISTEMAS DE INFORMAÇÃO', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'04865', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'11966', 'curso': 'AGRONOMIA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'10861', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'09926', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'09831', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'10937', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'11366', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2015.2', 'status': 'TRANCAMENTO'},
{'id':'70194', 'curso': 'BACHARELADO EM CIÊNCIAS ECONÔMICAS', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'70249', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'70514', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'09512', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'09684', 'curso': 'ECONOMIA DOMÉSTICA', 'entrada': '2014.1', 'status': 'MATRICULADO'},
{'id':'70614', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'07381', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'11562', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'10817', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'07151', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'11704', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'12849', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'08889', 'curso': 'AGRONOMIA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'05358', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'70597', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'70612', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'70899', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'11927', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'08381', 'curso': 'BACHARELADO EM CIÊNCIAS DO CONSUMO', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'11763', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'06053', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'12692', 'curso': 'BACHARELADO EM CIÊNCIAS DO CONSUMO', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'09795', 'curso': 'ZOOTECNIA', 'entrada': '2013.2', 'status': 'MATRICULADO'},
{'id':'03858', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'29914', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'03069', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'09535', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'04221', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'06627', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'11391', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'12153', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'05457', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2013.2', 'status': 'MATRICULADO'},
{'id':'10494', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'11921', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'10599', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2016.2', 'status': 'FORMADO'},
{'id':'10125', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'09382', 'curso': 'ENGENHARIA DE PESCA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'10148', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'61608', 'curso': 'BACHARELADO EM ADMINISTRAÇÃO', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'10500', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'70400', 'curso': 'ZOOTECNIA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'12227', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2016.2', 'status': 'TRANCAMENTO'},
{'id':'10710', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'11017', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'09095', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'10099', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'11260', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'10140', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'10896', 'curso': 'BACHARELADO EM SISTEMAS DE INFORMAÇÃO', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'11951', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'08487', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'11806', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'11394', 'curso': 'BACHARELADO EM ADMINISTRAÇÃO', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'12569', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'11465', 'curso': 'LICENCIATURA EM FÍSICA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'11361', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'08484', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2013.2', 'status': 'MATRICULADO'},
{'id':'10833', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2013.2', 'status': 'FORMADO'},
{'id':'11389', 'curso': 'AGRONOMIA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'10063', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'07136', 'curso': 'BACHARELADO EM ADMINISTRAÇÃO', 'entrada': '2014.1', 'status': 'MATRICULADO'},
{'id':'03067', 'curso': 'BACHARELADO EM GASTRONOMIA', 'entrada': '2014.1', 'status': 'FORMADO '},
{'id':'06407', 'curso': 'BACHARELADO EM CIÊNCIAS ECONÔMICAS', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'08910', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'12672', 'curso': 'BACHARELADO EM CIÊNCIAS DO CONSUMO', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'07964', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2010.2', 'status': 'MATRICULADO'},
{'id':'11628', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'11282', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'09374', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'10894', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'12003', 'curso': 'AGRONOMIA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'11460', 'curso': 'BACHARELADO EM CIÊNCIAS ECONÔMICAS', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'07703', 'curso': 'ZOOTECNIA', 'entrada': '2018.2', 'status': 'DESISTENCIA'},
{'id':'09178', 'curso': 'BACHARELADO EM CIÊNCIAS ECONÔMICAS', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'09163', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'07525', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'12045', 'curso': 'AGRONOMIA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'07738', 'curso': 'AGRONOMIA', 'entrada': '2014.1', 'status': 'MATRICULADO'},
{'id':'10943', 'curso': 'AGRONOMIA', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'70870', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'09249', 'curso': 'BACHARELADO EM ADMINISTRAÇÃO', 'entrada': '2015.2', 'status': 'FORMADO'},
{'id':'08642', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'11271', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'05460', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'10240', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'09629', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'11961', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'70594', 'curso': 'BACHARELADO EM GASTRONOMIA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'70516', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'10504', 'curso': 'BACHARELADO EM SISTEMAS DE INFORMAÇÃO', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'70277', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'11346', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2017.1', 'status': 'FORMADO'},
{'id':'06126', 'curso': 'BACHARELADO EM CIÊNCIAS ECONÔMICAS', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'10851', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'05400', 'curso': 'ECONOMIA DOMÉSTICA', 'entrada': '2016.1', 'status': 'DESISTENCIA'},
{'id':'06863', 'curso': 'LICENCIATURA EM FÍSICA', 'entrada': '2011.2', 'status': 'MATRICULADO'},
{'id':'05690', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2014.1', 'status': 'MATRICULADO'},
{'id':'08117', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2012.1', 'status': 'MATRICULADO'},
{'id':'12370', 'curso': 'AGRONOMIA', 'entrada': '2018.1', 'status': 'DESISTENCIA'},
{'id':'22786', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'07345', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2012.1', 'status': 'FORMADO'},
{'id':'09594', 'curso': 'BACHARELADO EM SISTEMAS DE INFORMAÇÃO', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'11563', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2014.1', 'status': 'MATRICULADO'},
{'id':'10376', 'curso': 'BACHARELADO EM CIÊNCIAS DO CONSUMO', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'06297', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'12666', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'10711', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2018.2', 'status': 'FORMADO'},
{'id':'06816', 'curso': 'AGRONOMIA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'10201', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'09012', 'curso': 'ECONOMIA DOMÉSTICA', 'entrada': '2017.1', 'status': 'FORMADO'},
{'id':'12295', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'11400', 'curso': 'ZOOTECNIA', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'70374', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'10581', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'12113', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'07683', 'curso': 'AGRONOMIA', 'entrada': '2016.2', 'status': 'FORMADO'},
{'id':'11370', 'curso': 'AGRONOMIA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'08138', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'04725', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'11175', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'10792', 'curso': 'ENGENHARIA DE PESCA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'10792', 'curso': 'AGRONOMIA', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'09805', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'12213', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'04122', 'curso': 'ECONOMIA DOMÉSTICA', 'entrada': '2013.1', 'status': 'MATRICULADO'},
{'id':'10152', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2013.2', 'status': 'MATRICULADO'},
{'id':'10774', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'12362', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'12910', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'11324', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2017.1', 'status': 'DESVINCULADO'},
{'id':'11705', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.1', 'status': 'FORMADO'},
{'id':'07598', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'11566', 'curso': 'AGRONOMIA', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'10440', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2014.1', 'status': 'MATRICULADO'},
{'id':'10081', 'curso': 'ECONOMIA DOMÉSTICA', 'entrada': '2013.1', 'status': 'MATRICULADO'},
{'id':'70244', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'70200', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'70542', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'06652', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'05826', 'curso': 'BACHARELADO EM CIÊNCIAS ECONÔMICAS', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'09253', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'09916', 'curso': 'ENGENHARIA DE PESCA', 'entrada': '2015.2', 'status': 'FORMADO'},
{'id':'70849', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'70419', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'12283', 'curso': 'LICENCIATURA EM FÍSICA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'09436', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2013.2', 'status': 'MATRICULADO'},
{'id':'11090', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'12581', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'70089', 'curso': 'BACHARELADO EM CIÊNCIAS DO CONSUMO', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'08297', 'curso': 'ZOOTECNIA', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'04859', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'03355', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2013.2', 'status': 'MATRICULADO'},
{'id':'10095', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2017.2', 'status': 'FORMADO'},
{'id':'11586', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'70206', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'12388', 'curso': 'AGRONOMIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'09708', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2017.1', 'status': 'FORMADO'},
{'id':'70603', 'curso': 'BACHARELADO EM CIÊNCIAS DO CONSUMO', 'entrada': '2018.1', 'status': 'DESISTENCIA'},
{'id':'10355', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2017.1', 'status': 'FORMADO'},
{'id':'10398', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'07603', 'curso': 'ZOOTECNIA', 'entrada': '2017.1', 'status': 'FORMADO'},
{'id':'79424', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2013.1', 'status': 'MATRICULADO'},
{'id':'10289', 'curso': 'BACHARELADO EM GASTRONOMIA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'10742', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'02786', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'08805', 'curso': 'ZOOTECNIA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'06646', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'03474', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2018.2', 'status': 'DESVINCULADO'},
{'id':'11049', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'10959', 'curso': 'AGRONOMIA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'03200', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'08003', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'70605', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'09932', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2017.2', 'status': 'FORMADO'},
{'id':'10183', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'10196', 'curso': 'AGRONOMIA', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'08978', 'curso': 'BACHARELADO EM SISTEMAS DE INFORMAÇÃO', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'09771', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'06939', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'11912', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'06427', 'curso': 'AGRONOMIA', 'entrada': '2013.2', 'status': 'MATRICULADO'},
{'id':'01629', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'12377', 'curso': 'AGRONOMIA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'06238', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'47569', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2013.1', 'status': 'MATRICULADO'},
{'id':'70165', 'curso': 'BACHARELADO EM CIÊNCIAS DO CONSUMO', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'11365', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'03495', 'curso': 'AGRONOMIA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'13459', 'curso': 'AGRONOMIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'11404', 'curso': 'ENGENHARIA DE PESCA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'12226', 'curso': 'AGRONOMIA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'70759', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'11036', 'curso': 'BACHARELADO EM GASTRONOMIA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'06671', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'70680', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'10343', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'11113', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'93629', 'curso': 'ZOOTECNIA', 'entrada': '2013.2', 'status': 'MATRICULADO'},
{'id':'10813', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2013.2', 'status': 'MATRICULADO'},
{'id':'07136', 'curso': 'BACHARELADO EM SISTEMAS DE INFORMAÇÃO', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'43908', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'12369', 'curso': 'BACHARELADO EM SISTEMAS DE INFORMAÇÃO', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'05665', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'09385', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'11971', 'curso': 'LICENCIATURA EM FÍSICA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'08709', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2014.1', 'status': 'MATRICULADO'},
{'id':'09963', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'09814', 'curso': 'AGRONOMIA', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'03314', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'13446', 'curso': 'AGRONOMIA', 'entrada': '2014.1', 'status': 'MATRICULADO'},
{'id':'10333', 'curso': 'BACHARELADO EM SISTEMAS DE INFORMAÇÃO', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'70729', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'11143', 'curso': 'BACHARELADO EM SISTEMAS DE INFORMAÇÃO', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'12172', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'11554', 'curso': 'LICENCIATURA EM FÍSICA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'12470', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'11215', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'81326', 'curso': 'BACHARELADO EM GASTRONOMIA', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'11413', 'curso': 'BACHARELADO EM CIÊNCIAS ECONÔMICAS', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'11568', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'08587', 'curso': 'ENGENHARIA DE PESCA', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'08771', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2012.1', 'status': 'MATRICULADO'},
{'id':'11823', 'curso': 'BACHARELADO EM CIÊNCIAS ECONÔMICAS', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'08952', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'08293', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'09953', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'12773', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'11751', 'curso': 'ZOOTECNIA', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'11191', 'curso': 'BACHARELADO EM ADMINISTRAÇÃO', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'70769', 'curso': 'AGRONOMIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'10022', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'08215', 'curso': 'BACHARELADO EM GASTRONOMIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'08792', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'09173', 'curso': 'BACHARELADO EM SISTEMAS DE INFORMAÇÃO', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'12364', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'09131', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2014.1', 'status': 'MATRICULADO'},
{'id':'11153', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2013.2', 'status': 'MATRICULADO'},
{'id':'11974', 'curso': 'AGRONOMIA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'41706', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'70680', 'curso': 'LICENCIATURA EM FÍSICA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'09841', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'12626', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'12323', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'10812', 'curso': 'AGRONOMIA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'12308', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'12001', 'curso': 'LICENCIATURA EM FÍSICA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'13680', 'curso': 'BACHARELADO EM CIÊNCIAS DO CONSUMO', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'02500', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2014.1', 'status': 'MATRICULADO'},
{'id':'05060', 'curso': 'ENGENHARIA DE PESCA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'10406', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'09643', 'curso': 'LICENCIATURA EM FÍSICA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'11337', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2017.2', 'status': 'DESISTENCIA'},
{'id':'09204', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'10324', 'curso': 'AGRONOMIA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'11158', 'curso': 'ENGENHARIA DE PESCA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'99832', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'11295', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'09068', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'09174', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'10791', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'07124', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2014.1', 'status': 'MATRICULADO'},
{'id':'09718', 'curso': 'AGRONOMIA', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'11444', 'curso': 'LICENCIATURA EM FÍSICA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'11818', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2015.2', 'status': 'FORMADO'},
{'id':'11970', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'10279', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'70819', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'05273', 'curso': 'ENGENHARIA DE PESCA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'10910', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'FORMADO'},
{'id':'05804', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2016.2', 'status': 'FORMADO'},
{'id':'09411', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'10928', 'curso': 'AGRONOMIA', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'12290', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'09625', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2013.2', 'status': 'MATRICULADO'},
{'id':'11966', 'curso': 'LICENCIATURA EM FÍSICA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'12939', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'14854', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'10955', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'11045', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'14425', 'curso': 'BACHARELADO EM CIÊNCIAS ECONÔMICAS', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'03771', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2013.1', 'status': 'MATRICULADO'},
{'id':'11414', 'curso': 'ECONOMIA DOMÉSTICA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'13805', 'curso': 'BACHARELADO EM GASTRONOMIA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'11229', 'curso': 'ZOOTECNIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'12353', 'curso': 'ZOOTECNIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'05636', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'10829', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'43229', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.2', 'status': 'FORMADO'},
{'id':'11232', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2014.1', 'status': 'MATRICULADO'},
{'id':'10468', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'12092', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'11167', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'10653', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'10789', 'curso': 'LICENCIATURA EM CIÊNCIAS AGRÍCOLAS', 'entrada': '2016.2', 'status': 'FORMADO'},
{'id':'12680', 'curso': 'ZOOTECNIA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'11370', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'04043', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'03909', 'curso': 'BACHARELADO EM GASTRONOMIA', 'entrada': '2016.1', 'status': 'FORMADO'},
{'id':'10468', 'curso': 'ZOOTECNIA', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'11122', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'09169', 'curso': 'BACHARELADO EM SISTEMAS DE INFORMAÇÃO', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'10761', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'11352', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'10318', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2016.1', 'status': 'FORMADO'},
{'id':'11832', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'10203', 'curso': 'AGRONOMIA', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'10097', 'curso': 'AGRONOMIA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'04802', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2015.2', 'status': 'FORMADO'},
{'id':'12979', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'04142', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'02412', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2015.2', 'status': 'FORMADO'},
{'id':'06552', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2015.2', 'status': 'TRANCAMENTO'},
{'id':'10728', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2014.1', 'status': 'FORMADO'},
{'id':'10788', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2014.1', 'status': 'MATRICULADO'},
{'id':'09224', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'08268', 'curso': 'BACHARELADO EM SISTEMAS DE INFORMAÇÃO', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'10483', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'10909', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'09882', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2014.1', 'status': 'FORMADO'},
{'id':'10758', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'10154', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2014.1', 'status': 'FORMADO'},
{'id':'10107', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'05422', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'10333', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'08192', 'curso': 'AGRONOMIA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'70184', 'curso': 'AGRONOMIA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'11917', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'11205', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2016.1', 'status': 'FORMADO'},
{'id':'10041', 'curso': 'BACHARELADO EM CIÊNCIAS ECONÔMICAS', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'12725', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'70300', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'11162', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'06338', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'11465', 'curso': 'ZOOTECNIA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'10778', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'10568', 'curso': 'BACHARELADO EM SISTEMAS DE INFORMAÇÃO', 'entrada': '2013.2', 'status': 'MATRICULADO'},
{'id':'10436', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2016.2', 'status': 'FORMADO'},
{'id':'05351', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'12003', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'10502', 'curso': 'AGRONOMIA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'11834', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'06129', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2013.2', 'status': 'MATRICULADO'},
{'id':'41296', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'12032', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'16557', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'70356', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'11001', 'curso': 'ZOOTECNIA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'00932', 'curso': 'ZOOTECNIA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'07473', 'curso': 'ENGENHARIA DE PESCA', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'06400', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'11618', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'05595', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'10741', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'06629', 'curso': 'ZOOTECNIA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'10748', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2016.1', 'status': 'FORMADO'},
{'id':'10402', 'curso': 'AGRONOMIA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'06088', 'curso': 'AGRONOMIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'11903', 'curso': 'LICENCIATURA EM FÍSICA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'11791', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'08606', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'10900', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'02577', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2014.1', 'status': 'MATRICULADO'},
{'id':'42061', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2016.1', 'status': 'FORMADO'},
{'id':'07569', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'09598', 'curso': 'AGRONOMIA', 'entrada': '2014.1', 'status': 'FORMADO'},
{'id':'11425', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'11624', 'curso': 'BACHARELADO EM CIÊNCIAS ECONÔMICAS', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'11186', 'curso': 'ZOOTECNIA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'70614', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'70395', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'70299', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'11328', 'curso': 'LICENCIATURA EM FÍSICA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'08909', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'11735', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'12328', 'curso': 'ZOOTECNIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'10989', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'10733', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'06586', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'10909', 'curso': 'BACHARELADO EM ADMINISTRAÇÃO', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'05787', 'curso': 'ENGENHARIA DE PESCA', 'entrada': '2014.1', 'status': 'MATRICULADO'},
{'id':'10271', 'curso': 'BACHARELADO EM ADMINISTRAÇÃO', 'entrada': '2018.2', 'status': 'FORMADO'},
{'id':'11243', 'curso': 'ENGENHARIA DE PESCA', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'10386', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'10342', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'10518', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'11219', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'08521', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2017.2', 'status': 'FORMADO'},
{'id':'10738', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'10843', 'curso': 'AGRONOMIA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'11830', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'07397', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'11749', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'13275', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'10133', 'curso': 'AGRONOMIA', 'entrada': '2018.2', 'status': 'FORMADO'},
{'id':'12882', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'12561', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'70804', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'08887', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2014.1', 'status': 'MATRICULADO'},
{'id':'09937', 'curso': 'ZOOTECNIA', 'entrada': '2013.1', 'status': 'MATRICULADO'},
{'id':'70868', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'10303', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'04127', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'10835', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'70895', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'12770', 'curso': 'LICENCIATURA EM FÍSICA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'10035', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2012.1', 'status': 'MATRICULADO'},
{'id':'03493', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'01086', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'70371', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'11828', 'curso': 'AGRONOMIA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'04374', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'70283', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'09649', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'08806', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2018.2', 'status': 'FORMADO'},
{'id':'10798', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'10926', 'curso': 'ZOOTECNIA', 'entrada': '2018.2', 'status': 'FORMADO'},
{'id':'10976', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'70158', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'09809', 'curso': 'ENGENHARIA DE PESCA', 'entrada': '2017.2', 'status': 'DESISTENCIA'},
{'id':'10603', 'curso': 'BACHARELADO EM ADMINISTRAÇÃO', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'12237', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'10424', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'70567', 'curso': 'MEDICINA VETERINÁRIA - UAG', 'entrada': '2018.2', 'status': 'TRANCAMENTO'},
{'id':'10361', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'12033', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'09786', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'11550', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'71084', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2018.2', 'status': 'DESVINCULADO'},
{'id':'70982', 'curso': 'BACHARELADO EM GASTRONOMIA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'10198', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'70562', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'10514', 'curso': 'LICENCIATURA EM CIÊNCIAS AGRÍCOLAS', 'entrada': '2018.2', 'status': 'FORMADO'},
{'id':'11327', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'70293', 'curso': 'BACHARELADO EM CIÊNCIAS DO CONSUMO', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'70159', 'curso': 'AGRONOMIA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'93360', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'05426', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'10275', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'01444', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2013.1', 'status': 'MATRICULADO'},
{'id':'11919', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'10443', 'curso': 'AGRONOMIA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'09738', 'curso': 'BACHARELADO EM CIÊNCIAS ECONÔMICAS', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'10201', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2013.2', 'status': 'MATRICULADO'},
{'id':'10623', 'curso': 'LICENCIATURA EM CIÊNCIAS AGRÍCOLAS', 'entrada': '2018.2', 'status': 'FORMADO'},
{'id':'71457', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'11137', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2018.2', 'status': 'FORMADO'},
{'id':'12422', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'10524', 'curso': 'AGRONOMIA', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'10709', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2017.2', 'status': 'FORMADO'},
{'id':'08771', 'curso': 'ZOOTECNIA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'10795', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'70439', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'70974', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'70544', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'08450', 'curso': 'ZOOTECNIA', 'entrada': '2018.1', 'status': 'FORMADO'},
{'id':'11236', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2014.1', 'status': 'MATRICULADO'},
{'id':'70226', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'11394', 'curso': 'AGRONOMIA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'12682', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'06203', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'10513', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'FORMADO'},
{'id':'10628', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2013.1', 'status': 'MATRICULADO'},
{'id':'03960', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2015.2', 'status': 'FORMADO'},
{'id':'08227', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'10751', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2013.2', 'status': 'MATRICULADO'},
{'id':'12568', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'07428', 'curso': 'BACHARELADO EM CIÊNCIAS DO CONSUMO', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'09999', 'curso': 'ENGENHARIA DE PESCA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'10874', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'70353', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'11020', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'10556', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'45981', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2014.1', 'status': 'MATRICULADO'},
{'id':'03865', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'04879', 'curso': 'AGRONOMIA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'08458', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'11211', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'11254', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'70411', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'70681', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'11670', 'curso': 'AGRONOMIA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'11519', 'curso': 'ZOOTECNIA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'11273', 'curso': 'BACHARELADO EM CIÊNCIAS ECONÔMICAS', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'11481', 'curso': 'AGRONOMIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'70581', 'curso': 'AGRONOMIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'10004', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2017.2', 'status': 'FORMADO'},
{'id':'09903', 'curso': 'LICENCIATURA EM FÍSICA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'10713', 'curso': 'BACHARELADO EM GASTRONOMIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'70741', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'12928', 'curso': 'LICENCIATURA EM FÍSICA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'11281', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'12525', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'13015', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'70606', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'10339', 'curso': 'AGRONOMIA', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'10336', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'10198', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2014.1', 'status': 'MATRICULADO'},
{'id':'11292', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'10425', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'09929', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'09749', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'70240', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'11590', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'06247', 'curso': 'MEDICINA VETERINÁRIA - UAG', 'entrada': '2015.2', 'status': 'MATRICULA VINCULO '},
{'id':'70206', 'curso': 'BACHARELADO EM CIÊNCIAS ECONÔMICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'70212', 'curso': 'AGRONOMIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'10753', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'10266', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'70581', 'curso': 'ZOOTECNIA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'12020', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'70822', 'curso': 'ZOOTECNIA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'10077', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'12011', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2017.1', 'status': 'DESVINCULADO'},
{'id':'07777', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'08396', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'10388', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'12973', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'09993', 'curso': 'BACHARELADO EM CIÊNCIAS DO CONSUMO', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'09197', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'11872', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'07873', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'13048', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'12151', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'09572', 'curso': 'LICENCIATURA EM COMPUTAÇÃO', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'10842', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'10771', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'09536', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2016.1', 'status': 'FORMADO'},
{'id':'10763', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'09797', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'10541', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'10879', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'05466', 'curso': 'LICENCIATURA EM CIÊNCIAS AGRÍCOLAS', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'08910', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'11209', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'11234', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'09698', 'curso': 'AGRONOMIA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'05012', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'07125', 'curso': 'ECONOMIA DOMÉSTICA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'07560', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2013.2', 'status': 'MATRICULADO'},
{'id':'11912', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'09277', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2013.2', 'status': 'FORMADO'},
{'id':'11244', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2013.2', 'status': 'FORMADO'},
{'id':'10148', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2014.1', 'status': 'MATRICULADO'},
{'id':'10813', 'curso': 'AGRONOMIA', 'entrada': '2015.2', 'status': 'DESLIGAMENTO'},
{'id':'70389', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'12423', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'10644', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'FORMADO'},
{'id':'70373', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'11346', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'11828', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'05886', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'08263', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'10187', 'curso': 'BACHARELADO EM CIÊNCIAS DO CONSUMO', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'12225', 'curso': 'AGRONOMIA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'70433', 'curso': 'ECONOMIA DOMÉSTICA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'09566', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'11057', 'curso': 'AGRONOMIA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'11814', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'08190', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'07580', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'10640', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'70265', 'curso': 'BACHARELADO EM SISTEMAS DE INFORMAÇÃO', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'07622', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2014.1', 'status': 'MATRICULADO'},
{'id':'70429', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'70966', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'46947', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'12298', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'11397', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2017.1', 'status': 'DESVINCULADO'},
{'id':'12607', 'curso': 'LICENCIATURA EM FÍSICA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'11283', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'11560', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'12801', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'00878', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.2', 'status': 'FORMADO'},
{'id':'06614', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2017.2', 'status': 'FORMADO'},
{'id':'70791', 'curso': 'BACHARELADO EM GASTRONOMIA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'09852', 'curso': 'BACHARELADO EM CIÊNCIAS DO CONSUMO', 'entrada': '2016.2', 'status': 'TRANCAMENTO'},
{'id':'11720', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'09903', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'11371', 'curso': 'BACHARELADO EM GASTRONOMIA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'10825', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'10064', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'10234', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2018.1', 'status': 'FORMADO'},
{'id':'09823', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2013.2', 'status': 'MATRICULADO'},
{'id':'11909', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'11281', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2014.1', 'status': 'MATRICULADO'},
{'id':'04619', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'10871', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'11267', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'10346', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'11042', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'11406', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'70310', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'12730', 'curso': 'ZOOTECNIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'70417', 'curso': 'BACHARELADO EM CIÊNCIAS DO CONSUMO', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'70683', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'09161', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'70889', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'10507', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'11416', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'10574', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'07376', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'07688', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'10131', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'11360', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.2', 'status': 'FORMADO'},
{'id':'10350', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'05807', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'70304', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'70251', 'curso': 'ENGENHARIA DE PESCA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'11392', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'09805', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2013.1', 'status': 'MATRICULADO'},
{'id':'05943', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'10291', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2012.2', 'status': 'MATRICULADO'},
{'id':'09990', 'curso': 'LICENCIATURA EM FÍSICA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'11357', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'11746', 'curso': 'BACHARELADO EM SISTEMAS DE INFORMAÇÃO', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'11369', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'09255', 'curso': 'ZOOTECNIA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'69798', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'08933', 'curso': 'AGRONOMIA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'09297', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2015.2', 'status': 'TRANCAMENTO'},
{'id':'10801', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'08117', 'curso': 'LICENCIATURA EM CIÊNCIAS AGRÍCOLAS', 'entrada': '2016.2', 'status': 'DESVINCULADO'},
{'id':'11144', 'curso': 'AGRONOMIA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'11240', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'12456', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'12135', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'08116', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2015.2', 'status': 'FORMADO'},
{'id':'11241', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'09179', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'11449', 'curso': 'BACHARELADO EM CIÊNCIAS ECONÔMICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'10881', 'curso': 'BACHARELADO EM ADMINISTRAÇÃO', 'entrada': '2014.1', 'status': 'MATRICULADO'},
{'id':'09131', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'11002', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'10290', 'curso': 'BACHARELADO EM ADMINISTRAÇÃO', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'10348', 'curso': 'MEDICINA VETERINÁRIA - UAG', 'entrada': '2015.1', 'status': 'FORMADO'},
{'id':'71326', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'03019', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2015.1', 'status': 'TRANCAMENTO'},
{'id':'12095', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'08436', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2012.1', 'status': 'MATRICULADO'},
{'id':'10982', 'curso': 'BACHARELADO EM SISTEMAS DE INFORMAÇÃO', 'entrada': '2014.1', 'status': 'MATRICULADO'},
{'id':'07022', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2015.1', 'status': 'DESISTENCIA'},
{'id':'10508', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'14404', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'13018', 'curso': 'AGRONOMIA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'10190', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2013.2', 'status': 'MATRICULADO'},
{'id':'09697', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2013.2', 'status': 'FORMADO'},
{'id':'11613', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'12224', 'curso': 'ZOOTECNIA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'09721', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'10359', 'curso': 'ZOOTECNIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'10666', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'10707', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'70595', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'06869', 'curso': 'ECONOMIA DOMÉSTICA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'11267', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'11178', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'70319', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'07564', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2014.1', 'status': 'MATRICULADO'},
{'id':'15975', 'curso': 'BACHARELADO EM GASTRONOMIA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'08236', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'11807', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'70605', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'11253', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2014.1', 'status': 'MATRICULADO'},
{'id':'08871', 'curso': 'ENGENHARIA DE PESCA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'10360', 'curso': 'LICENCIATURA EM FÍSICA', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'71097', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'09894', 'curso': 'AGRONOMIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'10072', 'curso': 'ENGENHARIA DE PESCA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'08042', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2017.2', 'status': 'FORMADO'},
{'id':'10005', 'curso': 'AGRONOMIA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'10438', 'curso': 'LICENCIATURA EM COMPUTAÇÃO', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'04873', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2017.2', 'status': 'DESVINCULADO'},
{'id':'06016', 'curso': 'ZOOTECNIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'70357', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'09836', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'11878', 'curso': 'AGRONOMIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'12312', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'12030', 'curso': 'BACHARELADO EM SISTEMAS DE INFORMAÇÃO', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'08119', 'curso': 'ECONOMIA DOMÉSTICA', 'entrada': '2018.2', 'status': 'FORMADO'},
{'id':'12479', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'11947', 'curso': 'ENGENHARIA DE PESCA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'10795', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'11222', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'09638', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'12099', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'11490', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'11915', 'curso': 'LICENCIATURA EM FÍSICA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'10827', 'curso': 'ZOOTECNIA', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'12388', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'60004', 'curso': 'AGRONOMIA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'09379', 'curso': 'BACHARELADO EM SISTEMAS DE INFORMAÇÃO', 'entrada': '2014.1', 'status': 'MATRICULADO'},
{'id':'07101', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'08054', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2013.1', 'status': 'MATRICULADO'},
{'id':'11971', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2017.2', 'status': 'DESISTENCIA'},
{'id':'12013', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'70522', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'11467', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'11252', 'curso': 'AGRONOMIA', 'entrada': '2014.1', 'status': 'MATRICULADO'},
{'id':'09234', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2016.1', 'status': 'FORMADO'},
{'id':'06798', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'11562', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.1', 'status': 'DESVINCULADO'},
{'id':'11180', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICA', 'entrada': '2016.1', 'status': 'FORMADO'},
{'id':'10945', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'10862', 'curso': 'LICENCIATURA EM FÍSICA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'12263', 'curso': 'BACHARELADO EM CIÊNCIAS DO CONSUMO', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'11715', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'70468', 'curso': 'BACHARELADO EM CIÊNCIAS DO CONSUMO', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'70630', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'07690', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'11004', 'curso': 'BACHARELADO EM GASTRONOMIA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'13118', 'curso': 'LICENCIATURA EM COMPUTAÇÃO', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'11858', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'06544', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'71111', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'12294', 'curso': 'ZOOTECNIA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'11963', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2014.1', 'status': 'MATRICULADO'},
{'id':'08856', 'curso': 'ENGENHARIA DE PESCA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'07230', 'curso': 'ZOOTECNIA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'12163', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'12210', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'70174', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'03315', 'curso': 'BACHARELADO EM GASTRONOMIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'11369', 'curso': 'AGRONOMIA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'08979', 'curso': 'LICENCIATURA EM FÍSICA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'70372', 'curso': 'ZOOTECNIA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'12987', 'curso': 'ZOOTECNIA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'11297', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'12377', 'curso': 'LICENCIATURA EM COMPUTAÇÃO', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'70394', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'70683', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'70248', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'07216', 'curso': 'BACHARELADO EM SISTEMAS DE INFORMAÇÃO', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'10921', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'08614', 'curso': 'AGRONOMIA', 'entrada': '2013.2', 'status': 'MATRICULADO'},
{'id':'70425', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'12747', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'12465', 'curso': 'ZOOTECNIA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'06801', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'09796', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'12366', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'12290', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'70870', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'11369', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'11561', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'12283', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'09791', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'11920', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'70824', 'curso': 'AGRONOMIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'07954', 'curso': 'LICENCIATURA EM FÍSICA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'10060', 'curso': 'ZOOTECNIA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'08646', 'curso': 'LICENCIATURA EM COMPUTAÇÃO', 'entrada': '2013.2', 'status': 'MATRICULADO'},
{'id':'11110', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'05453', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'11942', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'11015', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'70455', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'10678', 'curso': 'BACHARELADO EM GASTRONOMIA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'09912', 'curso': 'BACHARELADO EM CIÊNCIAS DO CONSUMO', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'12008', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'12943', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'10914', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'08358', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'70620', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'12385', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'11613', 'curso': 'BACHARELADO EM CIÊNCIAS ECONÔMICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'71200', 'curso': 'BACHARELADO EM GASTRONOMIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'12216', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'11103', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'09190', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'07144', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'09932', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'10947', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'08983', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'70299', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'70474', 'curso': 'LICENCIATURA EM FÍSICA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'12560', 'curso': 'LICENCIATURA EM FÍSICA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'11752', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'11232', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'11757', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'70166', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'11914', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'70972', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'11381', 'curso': 'ZOOTECNIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'09216', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'12793', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'70871', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'03275', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'10496', 'curso': 'BACHARELADO EM CIÊNCIAS ECONÔMICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'12477', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'70214', 'curso': 'BACHARELADO EM SISTEMAS DE INFORMAÇÃO', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'11344', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'71053', 'curso': 'BACHARELADO EM CIÊNCIAS DO CONSUMO', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'70797', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'71172', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'05074', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'11511', 'curso': 'BACHARELADO EM GASTRONOMIA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'11400', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'71047', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'13336', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'11885', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'71218', 'curso': 'BACHARELADO EM GASTRONOMIA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'70266', 'curso': 'LICENCIATURA EM FÍSICA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'70930', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'70571', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'13549', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'70389', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'12997', 'curso': 'LICENCIATURA EM FÍSICA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'13020', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'11268', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'12855', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'71105', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'03941', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'70971', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'09810', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'08471', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2013.2', 'status': 'MATRICULADO'},
{'id':'13488', 'curso': 'ZOOTECNIA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'10151', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'10503', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'70237', 'curso': 'AGRONOMIA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'70927', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'13488', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'11924', 'curso': 'BACHARELADO EM SISTEMAS DE INFORMAÇÃO', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'07970', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'40985', 'curso': 'AGRONOMIA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'70619', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'70179', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.1', 'status': 'DESISTENCIA'},
{'id':'11927', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'14540', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'11750', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'70566', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'70531', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'70303', 'curso': 'BACHARELADO EM CIÊNCIAS DO CONSUMO', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'70981', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'12125', 'curso': 'BACHARELADO EM ADMINISTRAÇÃO', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'10309', 'curso': 'ENGENHARIA DE PESCA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'11835', 'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'13056', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'70943', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'09156', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'12980', 'curso': 'ZOOTECNIA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'13401', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'10158', 'curso': 'ZOOTECNIA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'12291', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'70776', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'10339', 'curso': 'BACHARELADO EM CIÊNCIAS DO CONSUMO', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'06211', 'curso': 'AGRONOMIA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'11922', 'curso': 'ENGENHARIA DE PESCA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'71326', 'curso': 'BACHARELADO EM ADMINISTRAÇÃO', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'71066', 'curso': 'BACHARELADO EM CIÊNCIAS DO CONSUMO', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'71057', 'curso': 'BACHARELADO EM ADMINISTRAÇÃO', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'70247', 'curso': 'BACHARELADO EM SISTEMAS DE INFORMAÇÃO', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'13689', 'curso': 'BACHARELADO EM ENGENHARIA AMBIENTAL', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'06493', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'13032', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'10864', 'curso': 'ENGENHARIA MECÂNICA - UACSA', 'entrada': '2018.1', 'status': 'DESISTENCIA'},
{'id':'11789', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'12235', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'12191', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'08268', 'curso': 'ENGENHARIA DE PESCA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'70807', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'70298', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'12474', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'10530', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'12899', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'13891', 'curso': 'AGRONOMIA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'70562', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'10623', 'curso': 'ZOOTECNIA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'38593', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'00907', 'curso': 'AGRONOMIA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'11766', 'curso': 'AGRONOMIA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'11468', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'86183', 'curso': 'AGRONOMIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'42566', 'curso': 'ALUNO CONSORCIO', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'70922', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'06620', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2013.2', 'status': 'MATRICULADO'},
{'id':'01426', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'08542', 'curso': 'LICENCIATURA EM COMPUTAÇÃO', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'11168', 'curso': 'AGRONOMIA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'10153', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'99030', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'52004', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'10850', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'05851', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'70445', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'09826', 'curso': 'BACHARELADO EM CIÊNCIAS ECONÔMICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'06684', 'curso': 'BACHARELADO EM CIÊNCIAS DO CONSUMO', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'70573', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'12750', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'11990', 'curso': 'ZOOTECNIA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'07381', 'curso': 'AGRONOMIA', 'entrada': '2014.2', 'status': 'MATRICULADO'},
{'id':'08189', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'12955', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'11374', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'11251', 'curso': 'AGRONOMIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'70431', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'70246', 'curso': 'ZOOTECNIA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'10882', 'curso': 'AGRONOMIA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'70294', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'11369', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2015.1', 'status': 'MATRICULADO'},
{'id':'09886', 'curso': 'BACHARELADO EM GASTRONOMIA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'70788', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'12080', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'13290', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'07401', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'12430', 'curso': 'LICENCIATURA EM MATEMÁTICA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'12938', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'12295', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'70358', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2017.1', 'status': 'MATRICULADO'},
{'id':'11794', 'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'12585', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'11096', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'03035', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'13002', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'11922', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'71196', 'curso': 'AGRONOMIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'05365', 'curso': 'ZOOTECNIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'10756', 'curso': 'LICENCIATURA EM PEDAGOGIA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'70808', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'11358', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'10509', 'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'12694', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'70159', 'curso': 'ZOOTECNIA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'09561', 'curso': 'BACHARELADO EM CIÊNCIAS DO CONSUMO', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'11719', 'curso': 'ENGENHARIA DE PESCA', 'entrada': '2018.1', 'status': 'MATRICULADO'},
{'id':'11921', 'curso': 'LICENCIATURA EM FÍSICA', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'11248', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'08873', 'curso': 'LICENCIATURA EM FÍSICA', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'10719', 'curso': 'ZOOTECNIA - UAG', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'11527', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'70610', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'11318', 'curso': 'LICENCIATURA EM HISTÓRIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'10847', 'curso': 'MEDICINA VETERINÁRIA - UAG', 'entrada': '2016.2', 'status': 'MATRICULADO'},
{'id':'03980', 'curso': 'ENGENHARIA DE PESCA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'07397', 'curso': 'BACHARELADO EM ADMINISTRAÇÃO PÚBLICA - UEDT', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'11639', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'70754', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'09547', 'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'entrada': '2015.2', 'status': 'MATRICULADO'},
{'id':'11284', 'curso': 'BACHARELADO EM CIÊNCIAS ECONÔMICAS', 'entrada': '2018.2', 'status': 'TRANCAMENTO'},
{'id':'10226', 'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2013.2', 'status': 'MATRICULADO'},
{'id':'11641', 'curso': 'ENGENHARIA DE PESCA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'10698', 'curso': 'LICENCIATURA EM QUÍMICA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'13057', 'curso': 'LICENCIATURA EM FÍSICA', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'10349', 'curso': 'ENGENHARIA DE PESCA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'70805', 'curso': 'BACHARELADO EM SISTEMAS DE INFORMAÇÃO', 'entrada': '2017.2', 'status': 'MATRICULADO'},
{'id':'11458', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'12841', 'curso': 'ZOOTECNIA', 'entrada': '2018.2', 'status': 'MATRICULADO'},
{'id':'11361', 'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'entrada': '2019.1', 'status': 'MATRICULADO'},
{'id':'08084', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'15388', 'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'22786', 'curso': 'ENGENHARIA FLORESTAL', 'entrada': '2016.1', 'status': 'MATRICULADO'},
{'id':'13887', 'curso': 'MEDICINA VETERINÁRIA', 'entrada': '2016.1', 'status': 'MATRICULADO'},
]

alunos.forEach(a => {
    console.log(a.entrada)
})