const cursos = [
    {'curso': 'AGRONOMIA', 'duracao': 10},
    {'curso': 'AGRONOMIA - UAG', 'duracao': 10},
    {'curso': 'AGRONOMIA - UAST', 'duracao': 10},
    {'curso': 'ALUNO EM REGIME ESPECIAL', 'duracao': 0},
    {'curso': 'BACHARELADO EM ADMINISTRAÇÃO', 'duracao': 8},
    {'curso': 'BACHARELADO EM ADMINISTRAÇÃO - UAST', 'duracao': 8},
    {'curso': 'BACHARELADO EM ADMINISTRAÇÃO PÚBLICA - UEDT', 'duracao': 0},
    {'curso': 'BACHARELADO EM AGROECOLOGIA', 'duracao': 9},
    {'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO', 'duracao': 9},
    {'curso': 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO - UAG', 'duracao': 9},
    {'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS', 'duracao': 8},
    {'curso': 'BACHARELADO EM CIÊNCIAS BIOLÓGICAS - UAST', 'duracao': 9},
    {'curso': 'BACHARELADO EM CIÊNCIAS DO CONSUMO', 'duracao': 8},
    {'curso': 'BACHARELADO EM CIÊNCIAS ECONÔMICAS', 'duracao': 8},
    {'curso': 'BACHARELADO EM CIÊNCIAS ECONÔMICAS - UAST', 'duracao': 9},
    {'curso': 'BACHARELADO EM CIÊNCIAS SOCIAIS', 'duracao': 8},
    {'curso': 'BACHARELADO EM ENGENHARIA AMBIENTAL', 'duracao': 10},
    {'curso': 'BACHARELADO EM GASTRONOMIA', 'duracao': 8},
    {'curso': 'BACHARELADO EM SISTEMAS DE INFORMAÇÃO', 'duracao': 10},
    {'curso': 'BACHARELADO EM SISTEMAS DE INFORMAÇÃO - UAST', 'duracao': 10},
    {'curso': 'BACHARELADO EM SISTEMAS DE INFORMAÇÃO - UEDT', 'duracao': 8},
    {'curso': 'ECONOMIA DOMÉSTICA', 'duracao': 8},
    {'curso': 'ENGENHARIA AGRICOLA E AMBIENTAL', 'duracao': 10},
    {'curso': 'ENGENHARIA CIVIL-UACSA', 'duracao': 10},
    {'curso': 'ENGENHARIA DA COMPUTAÇÃO - UABJ', 'duracao': 10},
    {'curso': 'ENGENHARIA DE ALIMENTOS - UAG', 'duracao': 10},
    {'curso': 'ENGENHARIA DE CONTROLE E AUTOMAÇÃO -UABJ', 'duracao': 10},
    {'curso': 'ENGENHARIA DE MATERIAIS - UACSA', 'duracao': 10},
    {'curso': 'ENGENHARIA DE PESCA', 'duracao': 10},
    {'curso': 'ENGENHARIA DE PESCA - UAST', 'duracao': 10},
    {'curso': 'ENGENHARIA ELÉTRICA - UACSA', 'duracao': 10},
    {'curso': 'ENGENHARIA ELETRÔNICA - UACSA', 'duracao': 10},
    {'curso': 'ENGENHARIA FLORESTAL', 'duracao': 11},
    {'curso': 'ENGENHARIA HÍDRICA - UABJ', 'duracao': 10},
    {'curso': 'ENGENHARIA MECÂNICA - UACSA', 'duracao': 10},
    {'curso': 'ENGENHARIA QUÍMICA - UABJ', 'duracao': 10},
    {'curso': 'LICENCIATURA EM ARTES VISUAIS - UEDT', 'duracao': 0},
    {'curso': 'LICENCIATURA EM CIÊNCIAS - BIOLÓGIA', 'duracao': 0},
    {'curso': 'LICENCIATURA EM CIÊNCIAS - FÍSICA', 'duracao': 8},
    {'curso': 'LICENCIATURA EM CIÊNCIAS - QUÍMICA', 'duracao': 8},
    {'curso': 'LICENCIATURA EM CIÊNCIAS AGRÍCOLAS', 'duracao': 6},
    {'curso': 'LICENCIATURA EM CIÊNCIAS BIOLÓGICAS', 'duracao': 10},
    {'curso': 'LICENCIATURA EM CIÊNCIAS SOCIAIS', 'duracao': 8},
    {'curso': 'LICENCIATURA EM COMPUTAÇÃO', 'duracao': 10},
    {'curso': 'LICENCIATURA EM COMPUTAÇAO - UEDT', 'duracao': 10},
    {'curso': 'LICENCIATURA EM ECONOMIA DOMESTICA', 'duracao': 8},
    {'curso': 'LICENCIATURA EM EDUCAÇÃO FÍSICA', 'duracao': 8},
    {'curso': 'LICENCIATURA EM FÍSICA', 'duracao': 8},
    {'curso': 'LICENCIATURA EM FÍSICA - UEDT', 'duracao': 0},
    {'curso': 'LICENCIATURA EM HISTÓRIA', 'duracao': 9},
    {'curso': 'LICENCIATURA EM HISTÓRIA - UEDT', 'duracao': 0},
    {'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E ESPANHOL', 'duracao': 9},
    {'curso': 'LICENCIATURA EM LETRAS - PORTUGUES E INGLÊS-UAG', 'duracao': 9},
    {'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS E INGLÊS-UAST', 'duracao': 9},
    {'curso': 'LICENCIATURA EM LETRAS - PORTUGUÊS-UEDT', 'duracao': 0},
    {'curso': 'LICENCIATURA EM MATEMÁTICA', 'duracao': 9},
    {'curso': 'LICENCIATURA EM PEDAGOGIA', 'duracao': 9},
    {'curso': 'LICENCIATURA EM PEDAGOGIA - UAG', 'duracao': 8},
    {'curso': 'LICENCIATURA EM PEDAGOGIA - UEDT', 'duracao': 0},
    {'curso': 'LICENCIATURA EM QUÍMICA', 'duracao': 10},
    {'curso': 'LICENCIATURA EM QUÍMICA - UAST', 'duracao': 10},
    {'curso': 'MEDICINA VETERINÁRIA', 'duracao': 11},
    {'curso': 'MEDICINA VETERINÁRIA - UAG', 'duracao': 11},
    {'curso': 'ZOOTECNIA', 'duracao': 11},
    {'curso': 'ZOOTECNIA - UAG', 'duracao': 10},
    {'curso': 'ZOOTECNIA - UAST', 'duracao': 10},
]

